---
- name: Install dependencies
  portage:
    package: "{{ item }}"
    update: yes
  with_items:
    - app-arch/unzip
  when: ansible_os_family == "Gentoo"
- name: Install dependencies
  apt:
    pkg:
      - unzip
  when: ansible_os_family == 'Debian'

- name: Stat cargo-make command
  stat:
    path: "{{ cargo_make_install_directory }}/cargo-make"
  register: cargo_make_command
- name: Install cargo-make command
  when: cargo_make_command.stat.executable is not defined
  block:
    - name: Create temporary directory for cargo-make
      tempfile:
        state: directory
      register: temporary_directory_for_cargo_make
      changed_when: false
    - name: Download and extract cargo-make for Linux
      when: ansible_system == "Linux" and ansible_architecture == "x86_64"
      unarchive:
        src: "https://github.com/sagiegurari/cargo-make/releases/download/{{ cargo_make.version }}/cargo-make-v{{ cargo_make.version }}-x86_64-unknown-linux-musl.zip" # noqa 204
        dest: "{{ temporary_directory_for_cargo_make.path }}"
        remote_src: true
        mode: 0644
    - name: Install cargo-make for Linux
      when: ansible_system == "Linux" and ansible_architecture == "x86_64"
      copy:
        remote_src: true
        src: "{{ temporary_directory_for_cargo_make.path }}/cargo-make-v{{ cargo_make.version }}-x86_64-unknown-linux-musl/cargo-make"
        dest: "{{ cargo_make_install_directory }}/"
        mode: a+rx
    - name: Download and extract cargo-make for macOS
      when: ansible_distribution == "MacOSX"
      unarchive:
        src: https://github.com/sagiegurari/cargo-make/releases/download/{{ cargo_make.version }}/cargo-make-v{{ cargo_make.version }}-x86_64-apple-darwin.zip
        dest: "{{ temporary_directory_for_cargo_make.path }}"
        remote_src: true
        mode: 0644
    - name: Install cargo-make for macOS
      when: ansible_distribution == "MacOSX"
      copy:
        remote_src: true
        src: "{{ temporary_directory_for_cargo_make.path }}/cargo-make-v{{ cargo_make.version }}-x86_64-apple-darwin/cargo-make"
        dest: "{{ cargo_make_install_directory }}/"
        mode: a+rx
