name: default
on: [push]

jobs:
  setup:
    strategy:
      matrix:
        os: [macos-10.15, ubuntu-20.04]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: pip3 install ansible ansible-lint
      - run: ansible-lint tests/test.yml
      - run: ansible-playbook -i localhost, -c local -u $(id -un) tests/test.yml
